# Generated by Django 4.2 on 2026-05-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlc_eats_app', '0003_option_menuitem_ingredients_orderitem_note_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
