# Generated by Django 6.0.5 on 2026-05-13 08:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc_eats_app', '0005_alter_category_id_alter_menuitem_id_alter_option_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='userorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tlc_eats_app.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('w_realizacji', 'W realizacji'), ('w_dostarczeniu', 'W dostarczeniu'), ('zakonczone', 'Zakończone')], default='active', max_length=20),
        ),
    ]
