# Generated by Django 6.0.5 on 2026-05-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc_eats_app', '0006_order_start_time_order_status_userorder_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_initiator',
            field=models.BooleanField(default=False),
        ),
    ]
