# Generated by Django 6.0.5 on 2026-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc_eats_app', '0007_user_is_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
