# Generated by Django 6.0.5 on 2026-05-14 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc_eats_app', '0008_restaurant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailySpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_specials', to='tlc_eats_app.restaurant')),
            ],
        ),
    ]
