# Generated by Django 6.0.5 on 2026-05-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc_eats_app', '0012_menuitem_image_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Nieopłacone'), ('pending', 'Oczekuje na potwierdzenie'), ('confirmed', 'Potwierdzone'), ('rejected', 'Odrzucone')], default='unpaid', max_length=20),
        ),
    ]
