# Generated by Django 6.0.5 on 2026-05-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc_eats_app', '0013_user_phone_number_userorder_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('collecting', 'Zbieranie zamówień'), ('in_progress', 'W trakcie realizacji'), ('in_delivery', 'W trakcie dostawy'), ('delivered', 'Dostarczone')], default='collecting', max_length=20),
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('collecting', 'Zbieranie zamówień'), ('in_progress', 'W trakcie realizacji'), ('in_delivery', 'W trakcie dostawy'), ('delivered', 'Dostarczone')], default='collecting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='tlc_eats_app.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc_eats_app.restaurant')),
            ],
        ),
    ]
