# Generated by Django 6.0.5 on 2026-05-21 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc_eats_app', '0014_order_delivery_status_restaurantorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc_eats_app.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc_eats_app.userorder')),
            ],
            options={
                'unique_together': {('user', 'user_order')},
            },
        ),
    ]
