# Generated by Django 6.0.5 on 2026-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc_eats_app', '0015_restaurantrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_restaurants',
            field=models.BooleanField(default=False),
        ),
    ]
